---
title: "X_spiracleAnalysis"
output: html_document
---

# Load libraries

```{r}
# Load tidyverse
library(tidyverse)

# Load brms and tidybayes for analysis and interpretation
library(brms)
library(tidybayes)

# Load ape, geiger, and phytools for phylogenetic tree wrangling
library(ape)
library(geiger)
library(phytools)
```

# Load data

```{r}
# Load csv
rayData <- read.csv("Data/Data_Processed/RayDataTrimmed.csv")

# Load phylogenetic trees
rayTrees <- read.nexus("Data/Data_Processed/PrunedTrimmedTrees.nex")
```

# Prepare data for analysis

```{r}
logData <- rayData %>%
  mutate(logSA = log10(SpiracleArea),
         # Convert Spiracle Length (SPL) to cm and log10
         SPL_cm = SpiracleLength / 10,
         logSPL = log10(SPL_cm)) %>%
  # Drop rows with NAs
  drop_na(logSA, logSPL) %>%
  # Remove species with less than 4 individuals
  group_by(Genus_species) %>%
  filter(n() > 3) %>%
  ungroup()
```

```{r}
# Set seed for reproducability
set.seed(130)
```

```{r}
# Sample out a single tree
tree <- sample(rayTrees, 1)[[1]]

# View which species are a mismatch between the tree and data
diffNames <- name.check(tree, logData, logData$Genus_species)
# (should return a list of 141 species in tree but not in data)

# Keep only tips that are present in the data
tree <- drop.tip(tree,
                 setdiff(tree$tip.label, logData$Genus_species))

# Check names again (should return "OK")
diffNames <- name.check(tree, logData, logData$Genus_species)

# Keep only species present in the tree
logData <- logData[logData$Genus_species %in% tree$tip.label, ]
```

# Run brms model

```{r}
# Create variance covariance matrix
matrix <- ape::vcv(tree)

# Scale spiracle surface area (predictor (x))
scaledData <- logData %>%
  # "Scale" by centering only (since testing allometry)
  mutate(scaleSPL = scale(logSPL, center = TRUE, scale = FALSE))

# Build and run model
model <- brm(logSA ~ scaleSPL +
                     (1 + scaleSPL | gr(Genus_species, cov = matrix)),
          data = scaledData,
          data2 = list(matrix = matrix),
          family = gaussian,
          warmup = 4000, iter = 8000,
          cores = 2, control = list(adapt_delta = 0.95),
          save_pars = save_pars(all = TRUE))

summary(model)

# Save brms object
saveRDS(model, "Results/brmsOutputs/spiracle_SA.rds")
```

```{r}
# Optional: load model if revisting script
model <- readRDS("Results/brmsOutputs/spiracle_SA.rds")
```


```{r}
model_slopes <- model %>%
  # Get "global" posterior draws
  spread_draws(b_scaleSPL,
    # Get species level posterior draws
    r_Genus_species[Genus_species, term]) %>%
  # Filter for slopes (remove Intercept)
  filter(term == "scaleSPL") %>%
  # Calculate species' "true" slope based on global slope + relative to "global" slope
  mutate(slope = b_scaleSPL + r_Genus_species)

# Summarize by species
model_summary <- model_slopes %>%
  median_qi(slope, .width = 0.95) %>%
  # Replace _ with "" in species names
  mutate(Genus_species = str_replace_all(Genus_species, "_", " "),
         # Flag species that deviate from expectations
         significant = case_when(
           .lower > 2 ~ "Above",
           .upper < 2 ~ "Below",
           TRUE       ~ "Equal"))
```

```{r}
model_order <- c("Below", "Equal", "Above")
```

```{r}
# Order by significance then coefficient
model_sorted <- model_summary %>%
  arrange(factor(significant, levels = model_order), slope) %>%
  mutate(Genus_species = fct_inorder(Genus_species))
```

```{r}
coefPlot <- ggplot(model_sorted, aes(x = slope, y = Genus_species, 
                                     color = significant)) +
  geom_vline(xintercept = 2, color = "grey20") +
  geom_errorbar(aes(xmin = .lower, xmax = .upper),
                 width = 0) +
  geom_point(size = 2.5) +
  scale_color_manual(values = c("Above" = "#008080",
                                "Equal" = "grey80",
                                "Below" = "#ca562c")) +
  labs(x = "",
       y = "") +
  theme_classic() +
  theme(axis.text.y = element_text(face = "italic",
                                   size = 6),
        legend.position = "none")

ggsave("Results/Figures/FigureS1.png", coefPlot,
       width = 8, height = 10)
```

# Facet plot

```{r}
# Get the global mean used for centering
SPL_mean <- mean(scaledData$logSPL)

# Make a prediction grid
indPredict <- scaledData %>%
  group_by(Genus_species) %>%
  summarise(
    min_x = min(logSPL, na.rm = TRUE),
    max_x = max(logSPL, na.rm = TRUE),
    .groups = "drop") %>%
  crossing(logSPL = seq(min(scaledData$logSPL, na.rm = TRUE),
                        max(scaledData$logSPL, na.rm = TRUE),
                        length.out = 100)) %>%
  filter(logSPL >= min_x, logSPL <= max_x) %>%
  # Recreate scaleDW by centering so it can be "found"
  mutate(scaleSPL = logSPL - SPL_mean) %>%
  select(Genus_species, logSPL, scaleSPL)

# Draw from the posterior
SA_preds <- model %>%
  add_epred_draws(newdata = indPredict,
                  ndraws = 100)

# Summarize
SA_preds_sum <- SA_preds %>%
  group_by(Genus_species, logSPL) %>%
  median_qi(.epred, .width = 0.95) %>%
  mutate(Genus_species = str_replace_all(Genus_species, "_", " ")) %>%
  # Left join significance
  left_join(model_summary, by = "Genus_species")
```

```{r}
# Join significance status
namedData <- scaledData %>%
  # Replace _ with "" in species names
  mutate(Genus_species = str_replace_all(Genus_species, "_", " "))

namedData <- namedData %>%
  # Left join significance
  left_join(model_summary, by = "Genus_species")
```


```{r}
indPlot <- ggplot(namedData, aes(x = logSPL, y = logSA, 
                               color = significant)) +
  geom_line(data = SA_preds_sum, aes(x = logSPL, y = .epred,
                                         color = significant), linewidth = 0.5) +
  geom_point() +
  facet_wrap(~ Genus_species, scales = "free_x", ncol = 5) +
  scale_x_continuous(labels = function(x) round(10^x, 1),
                     breaks = function(x) seq(x[1], x[2], length.out = 3)) +
  scale_y_continuous(labels = function(y) round(10^y, 2)) +
  scale_color_manual(values = c("Above" = "#008080",
                                "Equal" = "grey80",
                                "Below" = "#ca562c")) +
  labs(x = "Spiracle Length (cm)",
       y = "Spiracle Surface Area") +
  theme_classic() +
  theme(axis.text = element_text(size = 6, color = "grey30"),
        # Set facet strip aesthetics
        strip.text = element_text(face = "italic", size = 8),
        strip.background = element_blank(),
        panel.spacing.x = unit(1, "lines"),
        legend.position = "none")

ggsave("Results/Figures/FigureS2.png", indPlot,
       width = 8.5, height = 11)
```

# Plot species

```{r}
# Aesthetics
# Set colors for each family
family_colors <- c(
  # Rajiformes - blues
  "Anacanthobatidae" = "#023e8a",
  "Arhynchobatidae" = "#0077b6",
  "Gurgesiellidae" = "#00b4d8",
  "Rajidae" = "#ade8f4",
  # Rhinopristiformes - purples
  "Glaucostegidae" = "#17003e",
  "Pristidae" = "#4e246f",
  "Rhinidae" = "#652f90",
  "Rhinobatidae" = "#a874d2",
  "Trygonorrhinidae" = "#c5a3e1",
  "Zanobatidae" = "#ece0f5",
  # Myliobatiformes - reds and pinks
  "Aetobatidae" = "#490a1a",
  "Dasyatidae" = "#570e1a",
  "Gymnuridae" = "#761323",
  "Hexatrygonidae" = "#8a1729",
  "Mobulidae" = "#a31b30",
  "Myliobatidae" = "#C4203A",
  "Plesiobatidae" = "#DF3853",
  "Potamotrygonidae" = "#E66479",
  "Rhinopteridae" = "#ED909F",
  "Urolophidae" = "#F4BCC5",
  "Urotrygonidae" = "#FBE8EB",
  # Torpediniformes - oranges and yellows
  "Hypnidae" = "#db7c26",
  "Narcinidae" = "#ff7b00",
  "Narkidae" = "#fcc602",
  "Platyrhinidae" = "#ffec5c",
  "Torpedinidae" = "#ffffb7"
)
```

```{r}
# Species lines
# Make a prediction grid
model_pred <- scaledData %>%
  group_by(Genus_species) %>%
  summarise(
    min_x = min(scaleSPL, na.rm = TRUE),
    max_x = max(scaleSPL, na.rm = TRUE),
    .groups = "drop") %>%
  crossing(scaleSPL = seq(min(scaledData$scaleSPL, na.rm = TRUE),
                         max(scaledData$scaleSPL, na.rm = TRUE),
                         length.out = 100)) %>%
  filter(scaleSPL >= min_x, scaleSPL <= max_x) %>%
  select(Genus_species, scaleSPL)

# Draw from the posterior
model_SPL_preds <- model %>%
  add_epred_draws(newdata = model_pred,
                  ndraws = 100)

# Extract family
family <- scaledData %>%
  select(Genus_species, Family)

# Summarize
model_SPL_preds_sum <- model_SPL_preds %>%
  group_by(Genus_species, scaleSPL) %>%
  median_qi(.epred, .width = 0.95) %>%
  left_join(family, by = "Genus_species", relationship = "many-to-many")
```

```{r}
# Create "population" grid
grid_data <- data.frame(
  scaleSPL = seq(min(scaledData$scaleSPL), max(scaledData$scaleSPL), length.out = 100))

# Extract "population" predictions
global_predictions <- grid_data %>%
  add_epred_draws(model, re_formula = NA) %>%
  median_qi(.epred)
```

```{r}
spPlot <- ggplot(data = scaledData, aes(x = scaleSPL, y = logSA, color = Family)) +
  geom_line(data = global_predictions, aes(x = scaleSPL, y = .epred), color = "grey40",
            linewidth = 1) +
  geom_line(data = model_SPL_preds_sum, aes(x = scaleSPL, y = .epred, 
                                            group = Genus_species, 
                                            color = Family), linewidth = 0.5) +
  geom_point(alpha = 0.4, size = 2.5) +
  scale_color_manual(values = family_colors) +
  scale_x_continuous(labels = function(x) format(round(10^x, 1))) +
  scale_y_continuous(labels = function(y) format(round(10^y, 1))) +
  labs(x = "Spiracle Length (cm)",
       y = expression("Spiracle Surface Area (" * cm^2 * ")")) +
  theme_classic() +
  theme(legend.position = "none",
        axis.text = element_text(size = 12))

labelPlot <- spPlot +
  annotate("text", x = -0.6, y = -1.95, 
           label = "Interspecies Relationship (slope = 1.94)", 
           size = 4.2, color = "grey40") +
  # Torpediniformes
  annotate("text", x = -0.86, y = -1.21, label = "Spottail Sleeper Ray", 
           size = 4.5, color = "#fcc602") +
  annotate("text", x = -0.86, y = -1.27, label = "Narke dipterygia", 
           size = 4, fontface = "italic", color = "#fcc602") +
  # Rhinopristiformes
  annotate("text", x = 0.25, y = 1.06, label = "Bowmouth Guitarfish", 
           size = 4.5, color = "#652f90") +
  annotate("text", x = 0.25, y = 1, label = "Rhina ancylostomus", 
           size = 4, fontface = "italic", color = "#652f90") +
  # Rajiformes
  annotate("text", x = -0.42, y = -1.35, label = "Spotted Legskate", 
           size = 4.5, color = "#023e8a") +
  annotate("text", x = -0.42, y = -1.41, label = "Anacanthobatis marmorata", 
           size = 4, fontface = "italic", color = "#023e8a") +
  # Myliobatiformes
  annotate("text", x = 0.7, y = 0.55, label = "Common Eagle Ray", 
           size = 4.5, color = "#C4203A") +
  annotate("text", x = 0.7, y = 0.49, label = "Myliobatis aquila", 
           size = 4, fontface = "italic", color = "#C4203A")

labelPlot

ggsave("Results/Figures/Figure4.png", labelPlot, width = 10, height = 10)
```
