---
title: "X_gillSpiracleAnalysis"
output: html_document
---

# 1. Load libraries

```{r}
# Load tidyverse
library(tidyverse)

# Load brms and tidybayes for analysis and interpretation
library(brms)
library(tidybayes)

# Load ape, geiger, and phytools for phylogenetic tree wrangling
library(ape)
library(geiger)
library(phytools)

# Load rphylopic for plotting
library(rphylopic)
```

# 2. Load data

```{r}
# Load csv
rayData <- read.csv("Data/Data_Processed/RayDataTrimmed.csv")

# Load phylogenetic trees
rayTrees <- read.nexus("Data/Data_Processed/PrunedTrimmedTrees.nex")
```

# 3. Prepare data for analysis

```{r}
logData <- rayData %>%
  # log10 Spiracle Length (SPL) and Gill Slit Height (GSH)
  mutate(logSPL = log10(SpiracleLength),
         logGSH = log10(GSavg)) %>%
  # Drop rows with NAs
  drop_na(logSPL, logGSH) %>%
  # Remove species with less than 4 individuals
  group_by(Genus_species) %>%
  filter(n() > 3) %>%
  ungroup()
```

```{r}
# Set seed for reproducability
set.seed(130)
```

```{r}
# Sample out a single tree
tree <- sample(rayTrees, 1)[[1]]

# View which species are a mismatch between the tree and data
diffNames <- name.check(tree, logData, logData$Genus_species)
# (should return a list of species in tree but not in data)

# Keep only tips that are present in the data
tree <- drop.tip(tree,
                 setdiff(tree$tip.label, logData$Genus_species))

# Check names again (should return "OK")
diffNames <- name.check(tree, logData, logData$Genus_species)

# Keep only species present in the tree
logData <- logData[logData$Genus_species %in% tree$tip.label, ]
```

# 4. Analyze with brms

```{r}
# Create variance covariance matrix
matrix <- ape::vcv(tree)

# Scale spiracle length (predictor (x))
scaledData <- logData %>%
  # "Scale" by centering only
  mutate(scaleSPL = scale(logSPL, center = TRUE, scale = FALSE))

# Build and run model
model <- brm(logGSH ~ scaleSPL * PropulsionMethod +
                     (1 + scaleSPL | gr(Genus_species, cov = matrix)),
          data = scaledData,
          data2 = list(matrix = matrix),
          family = gaussian,
          warmup = 4000, iter = 8000,
          cores = 2, control = list(adapt_delta = 0.95),
          save_pars = save_pars(all = TRUE))

summary(model)

# Save brms object
saveRDS(model, "Results/brmsOutputs/SPL_GSH.rds")
```

```{r}
# Optional: load model if revisting script
model <- readRDS("Results/brmsOutputs/SPL_GSH.rds")
```

# 5. Plot

```{r}
propulsion_slopes <- model %>%
  spread_draws(b_scaleSPL,
               `b_scaleSPL:PropulsionMethodPectoralOscillation`,
               `b_scaleSPL:PropulsionMethodPectoralUndulation`) %>%
  mutate(slope_reference = b_scaleSPL,
         slope_oscillation = b_scaleSPL + `b_scaleSPL:PropulsionMethodPectoralOscillation`,
         slope_undulation = b_scaleSPL + `b_scaleSPL:PropulsionMethodPectoralUndulation`) %>%
  select(.draw,
         slope_reference,
         slope_oscillation,
         slope_undulation) %>%
  pivot_longer(cols = - .draw,
               names_to = "PropulsionMethod",
               values_to = "slope") %>%
  mutate(PropulsionMethod = recode(PropulsionMethod,
                                   slope_reference = "Caudal Propulsion",
                                   slope_oscillation = "Pectoral Oscillation",
                                   slope_undulation = "Pectoral Undulation"))

propulsion_summary <- propulsion_slopes %>%
  group_by(PropulsionMethod) %>%
  median_qi(slope, .width = 0.95)
```

```{r}
# Get phylopic images
caud <- get_phylopic(uuid = "68a96e12-78b2-4b38-a532-1bdfa05a07bc")
osc <- get_phylopic(uuid = "ebdc09b9-659e-40e7-9323-1ac53d650aa3") %>%
  rotate_phylopic(angle = -90)
und <- get_phylopic(uuid = "0596f8ce-e9a5-4481-9982-ad7599fc2cba") %>%
  rotate_phylopic(angle = -90)
```


```{r}
propulsionPlot <- ggplot(propulsion_slopes, 
                         aes(x = slope, 
                             y = fct_rev(fct_reorder(PropulsionMethod, 
                                                     slope, .desc = TRUE)),
                       fill = PropulsionMethod)) +
  geom_vline(xintercept = 1, color = "grey20", linewidth = 0.5) +
  geom_vline(xintercept = 0, color = "grey90", linewidth = 0.3) +
  stat_halfeye(.width = c(0.95), point_interval = mean_qi) +
  scale_fill_manual(values = c("Pectoral Oscillation" = "#f68362",
                               "Pectoral Undulation" = "#545e82",
                               "Caudal Propulsion" = "#9cc3ed")) +
  scale_x_continuous(breaks = -2:3) +
  labs(x = "",
       y = "") +
  annotate("text", x = -1, y = 3.4, label = "Pectoral Oscillation", 
           size = 5, color = "#f68362") +
  annotate("text", x = 1.21, y = 2.95, label = "1.21", 
           size = 4, color = "#f68362") +
  annotate("text", x = -1, y = 2.4, label = "Caudal Propulsion", 
           size = 5, color = "#9cc3ed") +
  annotate("text", x = 0.85, y = 1.95, label = "0.85", 
           size = 4, color = "#9cc3ed") +
    annotate("text", x = -1, y = 1.4, label = "Pectoral Undulation", 
           size = 5, color = "#545e82") +
  annotate("text", x = 0.84, y = 0.95, label = "0.84", 
           size = 4, color = "#545e82") +
  add_phylopic(x = -1, y = 3.7, img = osc, height = 0.4,
               fill = "#f68362") +
  add_phylopic(x = -1, y = 2.65, img = caud, height = 0.3,
               fill = "#9cc3ed") +
  add_phylopic(x = -1, y = 1.65, img = und, height = 0.3,
               fill = "#545e82") +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
        )

propulsionPlot

ggsave("Results/Figures/Figure7.png", propulsionPlot,
       width = 8, height = 9)
```