---
title: "X_phylogeneticAnalysis"
output: html_document
---

## Purpose

To visualize the phylogenetic pattern in ray traits.

### Step 1: Load libraries

Load the libraries used.

```{r}
# Load tidyverse for sanity
library(tidyverse)

# Load phytools, ape, and geiger for working with phylogenetic trees
library(phytools)
library(ape)
library(geiger)

# Load ggtree and ggtreeExtrafor plotting phylogenetic tree
library(ggtree)
library(ggtreeExtra)
library(ggnewscale)

# Load scico for color palettes
library(scico)

# Load plotting libraries
library(cowplot)
library(grid)
library(gridExtra)
```

### Step 2: Load files

Load:
* Nexus file (PrunedTrimmedTrees.nex) 
* Shark trait data (RayDataTrimmed.csv)

```{r}
# Read the tree file
rayTrees <- read.nexus("Data/Data_Processed/PrunedTrimmedTrees.nex")

# Use read.csv to load ray data
rayData <- read.csv("Data/Data_Processed/RayDataTrimmed.csv")
```

### Step 3: Take mean for each species

Duplicate rows are not allowed (i.e., there can only be 1 row per species)

```{r}
# Create rayMeans dataframe
rayMeans <- rayData %>%
  # Convert Circularity to numeric
  mutate(Circularity = as.numeric(Circularity)) %>%
  # Group by species
  group_by(Genus_species) %>%
  # Calculate mean values
  summarise(# Retain Order
    Order = first(Order),
    # Retain Family
    Family = first(Family),
    # Retain Ecomorphotype data
    Ecomorphotype = first(Ecomorphotype),
    PropulsionMethod = first(PropulsionMethod),
    # Calculate means
    Mean_SpiracleLength = mean((((SpiracleLength * 10)/DiscLength_CM) * 100), 
                               na.rm = TRUE),
    Mean_GSavg = mean((((GSavg* 10)/DiscLength_CM) * 100), na.rm = TRUE),
    Mean_Circularity = mean(Circularity, na.rm = TRUE)) %>%
  as.data.frame()
```

### Step 4: Sample a tree and make sure they match

```{r}
# Set seed for reproducability
set.seed(123)

# Sample a single tree from Trees
singleRayTree <- sample(rayTrees, 1)[[1]]

# Set row names as species names
rownames(rayMeans) <- rayMeans$Genus_species

# Check species with setdiff
setdiff(singleRayTree$tip.label, rownames(rayMeans))
# Should return "character (0)"
```

### Step 5: Plot tree

```{r}
# Create a named list of species per Order
order_groups <- split(rayMeans$Genus_species, rayMeans$Order)

# Get MRCA nodes
order_nodes <- sapply(order_groups, function(x) getMRCA(singleRayTree, x))
order_nodes

# Create colors for each Order
order_colors <- scico(n = length(order_nodes), palette = "lipari")
names(order_colors) <- names(order_nodes)
```

```{r}
# Get plotted data
tree_data <- phyloTree$data

# Compute y positions for all Orders
order_y <- sapply(names(order_nodes), function(o) {
  node_number <- order_nodes[o]
  tree_data$y[tree_data$node == node_number]
})

# Print node positions
order_y
```

```{r}
# Plot simple tree before we go wild (without ASR)
phyloTree <- ggtree(singleRayTree)

# Look at tree
phyloTree
```

```{r}
# Create tree with no lines so downstream hilights are behind branches
phyloTreeOrder <- ggtree(phyloTree, linewidth = 0,
                         alpha = 0)

for (o in names(order_nodes)) {
  phyloTreeOrder <- phyloTreeOrder +
    geom_hilight(node = order_nodes[o],
                 fill = order_colors[o],
                 alpha = 0.25)
}

phyloTreeOrder <- phyloTreeOrder +
  geom_tree(aes(color = trait), linewidth = 1) +
  scale_color_scico(palette = "corkO") +
  theme(legend.position = "none")
```

```{r}
# Create monster tree
phyloTreeFull <- phyloTree +
  # Ecomorphotype
  new_scale_fill() +
  geom_fruit(data = rayMeans,
             geom = geom_bar,
             mapping = aes(y = Genus_species, x = 1, 
                           fill = Ecomorphotype),
             orientation = "y",
             stat = "identity",
             pwidth = 0.05) +
  scale_fill_manual(values = c("Aquilopelagic" = "#e95e50",
                                "Planktitrophic" = "#f1aa98",
                                "Rajobenthic" = "#f3b600",
                                "Rajopelagic" = "#ffda8f",
                                "Rhinobenthic" = "#3fccbb",
                                "Torpedobenthic" = "#287271")) +
  # Propulsion Method
  new_scale_fill() +
  geom_fruit(data = rayMeans,
             geom = geom_bar,
             mapping = aes(y = Genus_species, x = 1,
                           fill = PropulsionMethod),
             orientation = "y",
             stat = "identity",
             pwidth = 0.05) +
  scale_fill_manual(values = c("Caudal Propulsion" = "#084C61",
                               "Pectoral Oscillation" = "#b92621",
                               "Pectoral Undulation" = "#e9ba00")) + 
  theme(legend.position = "inside",
        legend.position.inside = c(0.1, 0.9),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))

phyloTreeFull
```

```{r}
ggsave("Results/Figures/PhylogeneticTree.png", phyloTreeFull,
       width = 10, height = 20)
```
