---
title: "X_principalComponentAnalysis"
output: html_document
---
# Load libraries

```{r}
# Load tidyverse
library(tidyverse)

# Load vegan for Principal Component Analysis (PCA)
library(vegan)
```

# Load data

```{r}
# Load csv
rayData <- read.csv("Data/Data_Tidy/allMuseumRayData.csv")
```

# Process data 

```{r}
# Tidy data
raysClean <- rayData %>%
  # Filter for adults
  filter(Maturity == "Mature" |
         Maturity == "Subadult") %>%
  # Select columns to include in the PCA
  select(Genus_species, Ecomorphotype, PropulsionMethod, DiscWidth_CM, 
         DiscLength_CM, LengthToApex_CM, SpiracleLength, GSavg)
  # # Convert circularity to numeric
  # mutate(Circularity = as.numeric(Circularity)) %>%
  # # Remove individuals that have NAs
  # drop_na() %>%
  # # Tidy up Circularity column
  # filter(Circularity != "blank tiff",
  #        Circularity != "No photo")
```

Take an average for each species to reduce the influence of an uneven number of specimens per species.

```{r}
# Create rayMeans dataframe
rayMeans <- raysClean %>%
  # Group by species
  group_by(Genus_species) %>%
  summarise(Mean_DiscWidth = mean(DiscWidth_CM, na.rm = TRUE),
            Mean_DiscLength = mean(DiscLength_CM, na.rm = TRUE),
            Mean_LengthToApex = mean(LengthToApex_CM, na.rm = TRUE),
            Mean_SpiracleLength = mean(SpiracleLength, na.rm = TRUE),
            Mean_GSavg = mean(GSavg, na.rm = TRUE),
            # Mean_Circularity = mean(Circularity, na.rm = TRUE),
            # Retain Ecomorphotype data
            Ecomorphotype = first(Ecomorphotype),
            PropulsionMethod = first(PropulsionMethod))
```

Create proportions.

```{r}
rayProportions <- rayMeans %>%
  mutate(DiscRatio = Mean_DiscWidth/Mean_DiscLength,
         LengthToApex_DL = Mean_LengthToApex/Mean_DiscLength,
         SpiracleLength_DL = Mean_SpiracleLength/Mean_DiscLength,
         GillSlitHeight_DL = Mean_GSavg/Mean_DiscLength) %>%
  select(Genus_species, Ecomorphotype, PropulsionMethod, DiscRatio, # Mean_Circularity,
         LengthToApex_DL, SpiracleLength_DL, GillSlitHeight_DL)
```

# Run a PCA

```{r}
# Extract numeric columns
rayNumeric <- rayProportions[4:7]

# Run PCA
rayPCA <- rda(rayNumeric, scale = TRUE)
```

# Inspect results

```{r}
summary(rayPCA)
```

```{r}
# Extract coordinates for the first two components
pcaScores <- scores(rayPCA, choices = c(1, 2), display = "sites")

# Extract loadings for variables
loadings <- scores(rayPCA, choices = c(1, 2), display = "species")

# Bind to rayProportions
rays <- cbind(rayProportions, pcaScores)
```

```{r}
plotPCA <- ggplot(rays, aes(x = PC1, y = PC2,
                            color = PropulsionMethod,
                            shape = PropulsionMethod)) +
  geom_point(size = 3, alpha = 0.9) +
  scale_color_manual(values = c("Caudal Propulsion" = "#084C61",
                               "Pectoral Oscillation" = "#b92621",
                               "Pectoral Undulation" = "#e9ba00")) +
  scale_shape_manual(values = c("Pectoral Oscillation" = 17,
                                "Pectoral Undulation" = 19,
                                "Caudal Propulsion" = 15)) +
  labs(x = "PC1 (32.3% Variance Explained)",
       y = "PC2 (27.0% Variance Explained)",
       color = "Propulsion Method",
       shape = "Propulsion Method") +
  theme_classic() +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "inside",
        legend.position.inside = c(0.08, 0.9),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 11))

plotPCA
```

```{r}
# Save figure
ggsave("Results/Figures/PCA.png", plotPCA,
       height = 9, width = 16)
```

# View plot with characters

```{r}
plot(rayPCA, display = c("sites", "species"))
```
